package hzj.dao.mapper;

import hzj.dao.po.SysRoleResourcePermission;
import hzj.dao.po.SysRoleResourcePermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysRoleResourcePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource_permission
     *
     * @mbggenerated Fri Nov 04 11:00:20 CST 2016
     */
    int countByExample(SysRoleResourcePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource_permission
     *
     * @mbggenerated Fri Nov 04 11:00:20 CST 2016
     */
    int deleteByExample(SysRoleResourcePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource_permission
     *
     * @mbggenerated Fri Nov 04 11:00:20 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource_permission
     *
     * @mbggenerated Fri Nov 04 11:00:20 CST 2016
     */
    int insert(SysRoleResourcePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource_permission
     *
     * @mbggenerated Fri Nov 04 11:00:20 CST 2016
     */
    int insertSelective(SysRoleResourcePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource_permission
     *
     * @mbggenerated Fri Nov 04 11:00:20 CST 2016
     */
    List<SysRoleResourcePermission> selectByExample(SysRoleResourcePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource_permission
     *
     * @mbggenerated Fri Nov 04 11:00:20 CST 2016
     */
    SysRoleResourcePermission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource_permission
     *
     * @mbggenerated Fri Nov 04 11:00:20 CST 2016
     */
    int updateByExampleSelective(@Param("record") SysRoleResourcePermission record, @Param("example") SysRoleResourcePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource_permission
     *
     * @mbggenerated Fri Nov 04 11:00:20 CST 2016
     */
    int updateByExample(@Param("record") SysRoleResourcePermission record, @Param("example") SysRoleResourcePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource_permission
     *
     * @mbggenerated Fri Nov 04 11:00:20 CST 2016
     */
    int updateByPrimaryKeySelective(SysRoleResourcePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_resource_permission
     *
     * @mbggenerated Fri Nov 04 11:00:20 CST 2016
     */
    int updateByPrimaryKey(SysRoleResourcePermission record);
}